### ISSUE TITLE
Help with setting up Redbird and subdomains

### ISSUE THREAD

**Issue by geelenbert** [OptimalBits/redbird#100]
Hi guys,

Previously i used a docker container called "Https-portal" to manage my reverse proxy. But for now i'm going to steer away from docker for now. So i'm moving over to Redbird. 

On paper it looks perfect!

Well first of all let me tell you that i'm completely new to node, but i figured out some stuff already. 

I have a Ubuntu 16.04 server running an i have my  public 80 and 443 port forwarded to this server.
I want the server to do SSL offloading and connect to my internal hosted services (sabnzbd, nextcloud, tvheadend and much more).

Installed redbird on the server. Needed to tell ubuntu to install a newer version of NodeJS (ubuntu installed 4.4.2) but now i have nodejs 6 running. 

All went fine, created a `nodehttpsportal.js` and run it with `sudo node nodehttpsportal.js`
```
var proxy = require('redbird')({port: 80, ssl: {port:443}});


// Tvheadend HTTPS portal
proxy.register('tvheadend.mydomain.com', 'http://192.168.1.180:9981', {
	ssl: {
    letsencrypt: {
      email: 'mail@gmail.com', // Domain owner/admin email
      production: false, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!
    }
  }
});

// Sonarr HTTPS portal
proxy.register('sonarr.mydomain.com', 'http://192.168.1.175:8989', {
	ssl: {
    letsencrypt: {
      email: 'mail@gmail.com', // Domain owner/admin email
      production: false, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!
    }
  }
});

// Radarr HTTPS portal
proxy.register('radarr.mydomain.com', 'http://192.168.1.175:7878', {
	ssl: {
    letsencrypt: {
      email: 'mail@gmail.com', // Domain owner/admin email
      production: false, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!
    }
  }
});
```

when running the script i get all sorts of errors, and here is where my know how ends....

```
sudo node ./nodehttpsportal.js 
{"name":"redbird","hostname":"HttpsPortal","pid":2198,"level":30,"msg":"Listening to HTTPS requests on port 443","time":"2017-04-28T18:45:03.733Z","v":0}
{"name":"redbird","hostname":"HttpsPortal","pid":2198,"level":30,"msg":"Started a Redbird reverse proxy server on port 80","time":"2017-04-28T18:45:03.735Z","v":0}
Missing certificate path for Lets Encrypt
Missing certificate path for Lets Encrypt
Missing certificate path for Lets Encrypt
{"name":"redbird","hostname":"HttpsPortal","pid":2198,"level":50,"err":{"message":"140036334454592:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140036334454592:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-04-28T18:45:04.170Z","v":0}
{"name":"redbird","hostname":"HttpsPortal","pid":2198,"level":50,"err":{"message":"140036334454592:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140036334454592:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-04-28T18:45:05.313Z","v":0}
{"name":"redbird","hostname":"HttpsPortal","pid":2198,"level":50,"err":{"message":"140036334454592:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140036334454592:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-04-28T18:45:06.455Z","v":0}
```

**Comment by geelenbert** [comment]
I've been playing around with the settings and i'm getting better results. 

My config is now:
`var proxy = require('redbird')({
  port: 80,
  xfwd: false,
  letsencrypt: {
    path: "/home/httpsportal/redbird/certs",
    port: 3000
  },
  ssl: {
    port: 443,
    http2: true,
  }
});

proxy.register("tvheadend.mydomain.com", "http://192.168.1.180:9981", {
    ssl: {
    letsencrypt: {
      email: "myemail@gmail.com",
      production: false
      }
    }
});

proxy.register("unifi.mydomain.com", "http://192.168.1.101:8443", {
    ssl: {
    letsencrypt: {
      email: "myemail@gmail.com",
      production: false
      }
    }
});

proxy.register("homeautomation.mydomain.com", "http://192.168.1.102:8080", {
    ssl: {
    letsencrypt: {
      email: "myemail@gmail.com",
      production: false
      }
    }
});

proxy.register("sonarr.mydomain.com", "http://192.168.1.175:8989", {
    ssl: {
    letsencrypt: {
      email: "myemail@gmail.com",
      production: false
      }
    }
});`

But now i'm getting these errors:
`{"name":"redbird","hostname":"HttpsPortal","pid":26137,"level":50,"err":{"message":"140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-05-03T20:11:51.398Z","v":0}
{"name":"redbird","hostname":"HttpsPortal","pid":26137,"level":50,"err":{"message":"140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-05-03T20:11:52.597Z","v":0}
{"name":"redbird","hostname":"HttpsPortal","pid":26137,"level":50,"err":{"message":"140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-05-03T20:11:53.748Z","v":0}
{"name":"redbird","hostname":"HttpsPortal","pid":26137,"level":50,"err":{"message":"140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n","name":"Error","stack":"Error: 140594839029568:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:\n\n    at Error (native)"},"msg":"HTTPS Client  Error","time":"2017-05-03T20:11:54.900Z","v":0}`

**Comment by manast** [comment]
These kind of errors are usually a missmatch between what client supports for ciphers and the server. I recommend that you try a service like this: https://www.ssllabs.com/ that will help you determine if the server is correctly configured.

**Comment by dothem1337** [comment]
Any findings @geelenbert? I run into the same issue...

**Comment by dansteingart** [comment]
I'm finding that the root cause here is that redbird does not file subdomains under a shared cert but rather requests a new cert for each subdomain. Let's Encrypt has pretty strict quotas (not strict as in low number, but in tight policy) which limit how many certs a given domain or IP address can request overall and in a given amount of time.  

```
{ type: 'urn:acme:error:rateLimited',
  detail: 'Error creating new cert :: too many certificates already issued for: ***.***: see https://letsencrypt.org/docs/rate-limits/',
  status: 429 }

```

I there a way to instruct redbird to bundle subdomains under a single cert?

**Comment by manast** [comment]
@dansteingart no, that is not possible, and it is a limitation of Letsencrypt itself.
