### ISSUE TITLE
Question : Socket clustering

### ISSUE THREAD

**Issue by MatthieuHPP** [OptimalBits/redbird#108]
Hi,
Does Redbird handle the use of socket on a cluster  ?
Matthieu

**Comment by manast** [comment]
Sorry for the late response. Unfortunately I do not understand the question, so I guess the the answer would be that redbird does not support it.

**Comment by MatthieuHPP** [comment]
Many thanks for your reply. I apologize for being unclear.
Here is a link to the difficulty I was thinking about :
https://socket.io/docs/using-multiple-nodes/

**Comment by aek** [comment]
The question is unclear but the answer is Yes, it's load balancing of requests over multiple backend nodes is supported
So you could build your cluster behind Redbird by registering multiples nodes for the same domain/subdomain/url

**Comment by manast** [comment]
well, sticky sessions are not supported. I think it is a hack due to socket.io's connection algoritm. On the other hand if you use only the websockets transports, I think it will work properly.
