### ISSUE TITLE
Wildcard support?

### ISSUE THREAD

**Issue by fanjules** [OptimalBits/redbird#11]
I'm new to node and have recently installed redbird, the performance is superb!  However, there appears no way to register all sub-domains, they have to be done individually.  E.g.  With example.com when I goto www.example.com I get "Not found" unless I specifically register the www sub-domain too.  I note from the documentation that nodes url parser is used which also seems to offer no method of support, and the register options don't offer a solution either.  Am I doing something wrong or is this a current limitation?

**Comment by manast** [comment]
you are right that wildcard or regular expressions are not supported at the moment. I would have to add that maybe having a wildcard to accept all possible subdomains wouldn't be a good practice, but I agree that having the possibility to express aliases with regular expressions would be a nice addition.

**Comment by fanjules** [comment]
Many thanks for your prompt reply.  I'm confused as to why that might be bad practice, though there is a certain degree of inexperience and ignorance on my part.  One of my sites has different country codes as sub-domains for different languages (e.g. fr.example.com br.example.com cn.example.com).  Not a deal breaker as there are a finite number of countries.

Another case is where users can choose their own sub-domain for their web presence.  They all arrive at the same server, but now this functionality is broken until I am able to add some extra code to register/unregister the domains (again not a deal breaker, but a bit of extra work for a vintage legacy website).  Both could easily be solved with *.example.com, and need not even require use of regex, though allowing additional sub-domains to point elsewhere as an override would be essential.

Other than this minor thing totally blown away with the performance and reliability of Redbird.

**Comment by benjitastic** [comment]
Just switched to Redbird from https://www.npmjs.com/package/http-proxy.

It's great. The only missing piece for me also is wildcards like http-proxy supports.

Like 'www.*.domain.com'  : 'localhost:4000'

**Comment by benwasser** [comment]
Wildcard support is an absolute requirement for a host-based router. Is there any chance that this will be addressed in a near-future release?

**Comment by Raker** [comment]
I would greatly like to see this implemented so I could adopt this library in my application.

**Comment by taoyuan** [comment]
Thanks to @manast, I have implemented a project [evoxy](https://gihub.com/taoyuan/evoxy) envolved from [redbird](https://github.com/OptimalBits/redbird) with highlights:

- Out of the box command-line tool `evo` with yaml configuratio support (default: `/etc/evoxy/evoxy.yml`)
- Challenges `http-01` and `tls-sni-01` have been tested, and `dns-01` should work
- __Wildcard hostname__ support like `www.*.example.com`

Most of work based on [redbird](https://github.com/OptimalBits/redbird) and [node-letsencrypt](https://github.com/Daplie/node-letsencrypt). Thanks again.

**Comment by n4nagappan** [comment]
You can use custom resolvers 
```
// wildcard domain routing
function customResolver(host, url, req) {
  if( /.*\.example.com/.test( host ) ) {
    return "http://127.0.0.1:4000";
  }
};
customResolver.priority = 100;
proxy.addResolver(customResolver);
```

**Comment by manast** [comment]
Wildcards work now even with LetsEncrypt, however you will get one certificate per domain instead of a single wildcard certificate, as that would require the DNS challenge which is much more cumbersome to setup and slower than the HTTP challenge.
