### ISSUE TITLE
Host headers unable to reverse proxy to S3 bucket?

### ISSUE THREAD

**Issue by aendrew** [OptimalBits/redbird#139]
Hi,

I'm considering using Redbird for a project whereby I have a list of URLs in CloudFront-hosted S3 buckets and need to reverse proxy requests on a specific subdomain there.

```
proxy.register(
  'some-server.mysite.com', 
  'http://some-bucket.s3-website-eu-west-1.amazonaws.com/<really-long-unrelated-path>'
);
```

However, I get an AWS `404`, "NoSuchBucket: The specified bucket does not exist" error page, with `BucketName` set as `some-server.mysite.com`. I think this is because Redbird isn't changing the `Host` header to `some-bucket.s3-website-eu-west-1.amazonaws.com` — is there any way to get around this? [AWS docs on the Host header spec](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingSpecifyBucket) for reference.

**Comment by fcardona** [comment]
You might want to try this...
```
proxy.register(
    'some-server.mysite.com', 
    'http://some-bucket.s3-website-eu-west-1.amazonaws.com/<really-long-unrelated-path>',
    {
         useTargetHostHeader: true
    }
);
```
Source: https://github.com/OptimalBits/redbird/pull/7

**Comment by manast** [comment]
I have verified the proposed solution and it works well.
