### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by diogoviannaaraujo** [OptimalBits/redbird#15]
Im testing this library but it keeps printing every request on the screen,
any non verbose option?

**Comment by manast** [comment]
You can disable all the logging by passing ```bunyan: false``` to the options. Since it is based on bunyan you can also filter out the logs as you want: https://github.com/trentm/node-bunyan
Note that logging just consumes around 10% of the resources.

**Comment by manast** [comment]
Closing as this has been answered, although now we use pino which is much faster than Bunyan.
