### ISSUE TITLE
Getting IP Address of Client

### ISSUE THREAD

**Issue by fanjules** [OptimalBits/redbird#16]
This isn't so much an issue for me, but I've posted this here for the benefit of other users of Redbird.  When I moved to Redbird I assumed that I would not be able to access the IP of the client connections, as this was the case with my previous reverse proxy, where everybody had the same IP of 127.0.0.1.

However, I have since realized that Redbird implements the "x-forwarded-for" header, which gives the correct address, and thankfully most of the services I run can be modified to look at that header for it's IP address.  I have been using this header for a few weeks now with good results.  Hopefully this information proves useful to you.

I'm not sure if it's possible for the client to manipulate the x-forwarded-for header by sending their own, but I presume Redbird has complete control over it so thus x-forwarded-for should be considered reliable?

**Comment by manast** [comment]
the x-forward header is added by node-http-proxy so I assume it is quite reliable.
