### ISSUE TITLE
Can't get basic example to work on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by steve-taylor** [OptimalBits/redbird#17]
This works, tested by going to https://sensorypanel.net:

```
var fs = require('fs');

var http = require('http');
http.createServer(function(req, res) {
        res.writeHead(200, {'Content-Type': 'text/plain'});
        res.end('Hello World\n');
}).listen(80, '0.0.0.0');

var https = require('https');
var options = {
        key: fs.readFileSync('certs/sensorypanel.net/sensorypanel_net-key.pem'),
        cert: fs.readFileSync('certs/sensorypanel.net/sensorypanel_net.crt'),
        ca: fs.readFileSync('certs/ca_bundle.crt')
};
https.createServer(options, function(req, res) {
        res.writeHead(200, {'Content-Type': 'text/plain'});
        res.end('Hello SSL World\n');
}).listen(443, '0.0.0.0');
```

This doesn't:

```
var redbird = require('redbird'),
    http = require('http');

var proxy = redbird({
        port: 80,
        ssl: {
                port: 443,
                key: 'certs/sensorypanel.net/sensorypanel_net-key.pem',
                cert: 'certs/sensorypanel.net/sensorypanel_net.crt',
                ca: 'certs/ca_bundle.crt'
        }
});

proxy.register('sensorypanel.net', 'http://localhost:4001', {ssl: true});

http.createServer(function(req, res) {
        console.log('Got a request!');
        res.writeHead(200, {'Content-Type': 'text/plain'});
        res.end('Hello World\n');
}).listen(4001, '0.0.0.0');
```

The connection isn't refused immediately. It just hangs. I can still go around the proxy via http://sensorypanel.net:4001, which verifies the underlying HTTP service is working. The firewall is off.

Here's a sample of the log:

```
{"name":"redbird","hostname":"sensorypanel.net","pid":1370,"level":30,"msg":"Listening to HTTPS requests on port 443","time":"2015-08-26T04:46:05.919Z","v":0}
{"name":"redbird","hostname":"sensorypanel.net","pid":1370,"level":30,"msg":"80 'Started a Redbird reverse proxy server'","time":"2015-08-26T04:46:05.925Z","v":0}
{"name":"redbird","hostname":"sensorypanel.net","pid":1370,"level":30,"from":{"protocol":"http:","slashes":true,"auth":null,"host":"sensorypanel.net","port":null,"hostname":"sensorypanel.net","hash":null,"search":null,"query":null,"pathname":"/","path":"/","href":"http://sensorypanel.net/"},"to":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:4001","port":"4001","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/","path":"/","href":"http://localhost:4001/","sslRedirect":true,"useTargetHostHeader":false},"msg":"Registered a new route","time":"2015-08-26T04:46:05.931Z","v":0}
{"name":"redbird","hostname":"sensorypanel.net","pid":1370,"level":50,"err":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:664:25)\n    at TLSSocket.emit (events.js:107:17)\n    at TCP.close (net.js:485:12)","code":"ECONNRESET"},"msg":"HTTPS Client  Error","time":"2015-08-26T04:46:27.847Z","v":0}
{"name":"redbird","hostname":"sensorypanel.net","pid":1370,"level":50,"err":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:664:25)\n    at TLSSocket.emit (events.js:107:17)\n    at TCP.close (net.js:485:12)","code":"ECONNRESET"},"msg":"HTTPS Client  Error","time":"2015-08-26T04:46:41.931Z","v":0}
```

**Comment by manast** [comment]
The example looks correct by a quick look. Can you try to test using curl just to eliminate possible browser side effects? Does it work if you access the proxy using normal http?

**Comment by steve-taylor** [comment]
This works locally (bypasses the proxy):
* `curl -k http://localhost:4001`
* `curl -k http://sensorypanel.net:4001`

This doesn't work locally:
* `curl -k https://sensorypanel.net` (hangs, then "curl: (35) Unknown SSL protocol error in connection to sensorypanel.net:443")
* `curl -k https://localhost` (hangs)
* `curl -k https://127.0.0.1` (fails with "Not Found" response)
* `curl -k https://127.0.1.1` (fails with "Not Found" response)
* `curl -k https://0.0.0.0` (fails with "Not Found" response)
* `curl -k http://sensorypanel.net` (immediately returns empty response; log suggests a redirect occurred)

**Comment by steve-taylor** [comment]
Btw, thanks for the very quick response.

**Comment by steve-taylor** [comment]
All these return "Not Found":
* `curl -k http://127.0.0.1`
* `curl -k http://127.0.1.1`
* `curl -k http://0.0.0.0`

And this is what the log says:

```
{"name":"redbird","hostname":"sensorypanel.net","pid":2454,"level":40,"msg":"127.0.0.1 no valid route found for given source","time":"2015-08-26T06:32:21.328Z","v":0}
{"name":"redbird","hostname":"sensorypanel.net","pid":2454,"level":40,"msg":"127.0.1.1 no valid route found for given source","time":"2015-08-26T06:32:28.303Z","v":0}
{"name":"redbird","hostname":"sensorypanel.net","pid":2454,"level":40,"msg":"0.0.0.0 no valid route found for given source","time":"2015-08-26T06:32:40.036Z","v":0}
```

**Comment by manast** [comment]
I will take a deeper look at it this evening. There must be something subtle that we are missing.

**Comment by steve-taylor** [comment]
Thanks. I tried it just now on OS X and still get the same results.

**Comment by steve-taylor** [comment]
On the upside, there's now a [stackoverflow tag](http://stackoverflow.com/tags/redbird/info) :)

**Comment by kohsah** [comment]
I have a similar problem, "no route found to valid host" for accessing via a domain name. 

my server has multiple hostnames (set in /etc/hosts). redbird seems to like only the name set in /etc/hostname (and localhost) rather than all the mappings specified in /etc/hosts.

**Comment by rajkissu** [comment]
I'm experiencing the same problem as @steve-taylor. Any luck on a solution?

**Comment by rajkissu** [comment]
After some debugging, I found out that its because the `SNICallback` function being passed to the `HTTPS` proxy is returning undefined. I'm not sure what this means, as I'm not familiar with SSL much, but removing the function in question stops the socket from timing out.

For reference: https://github.com/OptimalBits/redbird/blob/4d50293169c2f7ebb61afd6481800d105ca57998/lib/proxy.js#L105-L107

It's a temporary fix, but I don't know if it'll break something else. Perhaps someone with a better understanding of this can shed some light on the matter?

**Comment by manast** [comment]
This issue was produced by a change in the tls.createServer API. Specifically on the call signature of the SNICallback: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
