### ISSUE TITLE
Thank you! 👏👏👏

### ISSUE THREAD

**Issue by oliver-moran** [OptimalBits/redbird#175]
Not an issue - I just want to say thank you. Excellent piece of software. So easy to use and does everything it promises. And I absolutely love the no-config Let's Encrypt support. Thank you! 👏👏👏

**Comment by archiebaer** [comment]
In that case, you can close this issue.

**Comment by manast** [comment]
@oliver-moran Thanks for the support.

**Comment by archiebaer** [comment]
If something is not an issue, then don't open an issue.
