### ISSUE TITLE
HTTP2 support?

### ISSUE THREAD

**Issue by capaj** [OptimalBits/redbird#18]
As far as I checked, currently there is no reverse proxy with http2 support, even though a lot of current browsers do support it: http://caniuse.com/#feat=http2

Could we get http2 support in redbird? Node.js already has https://github.com/molnarg/node-http2 so it should be quite possible, right? I am a fan of [JSPM](https://github.com/jspm/jspm-cli) and getting http2 to production server would be a huge deal for me and many others.

**Comment by tcoats** [comment]
@capaj What sort of proxying would you want to perform with http2?
e.g.

1. http2 front, proxy to http(s) backend
2. http2 front, proxy to http2 backend
3. http(s) front, proxy to http2 backend

I imagine it's use case number 1, however the other options are also useful.

**Comment by manast** [comment]
https://github.com/nodejitsu/node-http-proxy/pull/919

**Comment by manast** [comment]
Redbird supports http2 based on the built-in NodeJS http2 server.
