### ISSUE TITLE
would like xfwd to be false

### ISSUE THREAD

**Issue by gsjurseth** [OptimalBits/redbird#19]
If I change line 55 of index.js to:

      xfwd: opts.xfwd ? opts.xfwd : false,

instead of just:

    xfwd: true

Then I get the option of setting this to true if I prefer it that way. For my current use case I need this to be set to false or it breaks the process I'm connecting to. Is this a change y'all would consider making?

Thanks,

/geir

**Comment by manast** [comment]
I would consider that change, but it should be backwards compatible, meaning that default must be true, and it should be possible to disable it via an option.

**Comment by gsjurseth** [comment]
Sure, fair enough. Would you like me to fork or pull request? Or will you just make such a change?

**Comment by manast** [comment]
I am on a very busy period, so if you need this now it is better that you fix it and make a pull request...

**Comment by gsjurseth** [comment]
totally understand. I'll do a pull request and leave true as the default.

**Comment by gsjurseth** [comment]
Any chance you could look at and then approve my pull request? It leaves all existing functionality intact but makes the configuration I need optional.

/geir

**Comment by manast** [comment]
Sorry, I actually did miss the pull request. Its merged now.
