### ISSUE TITLE
Redirecting to specific file?

### ISSUE THREAD

**Issue by 0vermind** [OptimalBits/redbird#21]
Is possible to redirect every request in a directory to a specific file like a 404 page or image?

**Comment by manast** [comment]
It is not possible, but indeed a useful feature, I will consider adding it in the future.

**Comment by 0vermind** [comment]
great! Looking forward to test it. By the way, Redbird is an awesome project!

**Comment by manast** [comment]
You can use custom resolvers for this feature.
