### ISSUE TITLE
websocket proxy

### ISSUE THREAD

**Issue by diginfo** [OptimalBits/redbird#22]
This is similar to another post.

redbird is running on port 80, I am running express-ws on a server, where the http and ws ports are the same, i.e port 801.

I have proxied the hostname to the nodejs instance running on port 801, and I can make a websocket connection successfully using port 801 but I cannot make the ws connection on port 80.

I would rather not connect to ws on 801 as this means I need to expose the port, which i don't really want to do ?

The error reported by the client when trying to connect on port 80 is: 

    failed: Error during WebSocket handshake: Invalid status line

**Comment by niemes** [comment]
Any news about that ?
