### ISSUE TITLE
Corrupted images/data when using the http2 option

### ISSUE THREAD

**Issue by firstdorsal** [OptimalBits/redbird#225]
when using the http2 option with redbird and ssl everything worked fine until some of the jpg images on my websites got totally corrupted like that:

**corrupted:**
![image1](https://user-images.githubusercontent.com/10563452/64055469-eb985600-cb8c-11e9-9977-566d690c1fb2.jpg)
**original:**
![image](https://user-images.githubusercontent.com/10563452/64055470-eb985600-cb8c-11e9-8a4d-231a22c06435.jpg)

i have no idea why but turning it from true to false fixed it...
i tried everything else and finally after hours of research found out that this was the problem;

**Comment by valentinLecorps** [comment]
Same for me, have to disable http2 to make it works :/

**Comment by firstdorsal** [comment]
only occurs when using the compression middleware in express

**Comment by runekm** [comment]
This problem is probably caused by this issue: https://github.com/spdy-http2/node-spdy/issues/357 and it seems to me to affect all compressed content that is transferred with http2.

The problem apparently started with version 4.0.0 of spdy. Version 3.4.7 doesn't seem to have this problem.

**Comment by firstdorsal** [comment]
this was a cool project for the time but i have been using traefik and as expected it works much better for everything
