### ISSUE TITLE
Is redbird no longer maintained?

### ISSUE THREAD

**Issue by Reinitialized** [OptimalBits/redbird#267]
I've noticed its been over 10 months since the npm package has been updated, ~~but seems work is being continued within this repo. Is the npm variant no longer maintained, or is there a release waiting to be finished before updating?~~ and after further review, it seems progress on redbird has mostly grind to a halt. 

Is this project dead? Should I look into alternatives for my "production" applications?

**Comment by roslovets** [comment]
I have migrated form `redbird` to `greenlock-express`. At least it works with Node v14.15.0

**Comment by crossinghoods** [comment]
Having spent about a day trying to port over and simplify Redbird to Typescript I ended up going with **http-reverse-proxy-ts** instead (https://www.npmjs.com/package/http-reverse-proxy-ts)

If you are looking for a quick fix here is the code to help get you up and running - 2 files, as usual **npm install** then **node index.js**

**index.js**
```
"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const http_reverse_proxy_ts_1 = require("http-reverse-proxy-ts");
const logger = new http_reverse_proxy_ts_1.Logger();

const letsEncryptServerOptions = {
    noVerify: true
};

const httpReverseProxyOptions = {
    letsEncryptOptions: letsEncryptServerOptions,
    httpsOptions: {
        port: 443,
        certificates: {
            certificateStoreRoot: './certs'
        },
    },
    log: logger,
};

const routingOptions = {
    https: {
        redirectToHttps: true,
        letsEncrypt: {
            email: 'domain@maintainer.email..com', // Update this to the domain manager's email
            production: false, // put it to true when you've tested it
        }
    }
};

const proxy = new http_reverse_proxy_ts_1.HttpReverseProxy(httpReverseProxyOptions, http_reverse_proxy_ts_1.LetsEncryptUsingAcmeClient);

proxy.addRoute("https://www.example.com", "127.0.0.1:8000", routingOptions);
logger.info(null, "Proxy server started");
```
**package.json**
```
{
  "name": "quick-reverse-proxy-fix",

  "version": "1.0.0",
  "description": "Reverse Proxy used to forward requests to servers",
  "main": "index.js",
  "scripts": {
    "bp": "npm run build:prod",
    "develop": "tsc -w",
    "build:prod": "tsc -p tsconfig.prod.json"
  },
  "keywords": [
    "Reverse",
    "Proxy"
  ],
  "author": "Your name",
  "license": "MIT",
  "dependencies": {
    "http-reverse-proxy-ts": "^1.0.1"
  },
  "devDependencies": {
    "@types/node": "^14.14.9"
  }
}
```

**Comment by roslovets** [comment]
For my purposes I have created the simpliest [greenlock-proxy](https://github.com/Roslovets-Inc/greenlock-proxy).

Of course it's not so powerfull as redbird, but it's easier to use if you only interested in https reverse proxy with fully automatic Let's Encrypt handling.

**Comment by crossinghoods** [comment]
> For my purposes I have created the simpliest [greenlock-proxy](https://github.com/Roslovets-Inc/greenlock-proxy).
> 
> Of course it's not so powerfull as redbird, but it's easier to use if you only interested in https reverse proxy with fully automatic Let's Encrypt handling.

Tested your solution, works very well!  Only caveat is using expressJS behind the scenes which is an extra layer with lots of dependencies.  I might start a new repo based on your implementation 👍

**Comment by roslovets** [comment]
> I might start a new repo based on your implementation 👍

It would be great, because I'm not a professional web developer.

**Comment by crossinghoods** [comment]
> > I might start a new repo based on your implementation 👍
> 
> It would be great, because I'm not a professional web developer.

Done a great job even though you claim to not be a professional web developer.  I've seen professionals done way worse than what you've produced!

**Comment by Starystars67** [comment]
I too would like to know if this project is dead now. I'm about to be making quite a sizeable upgrade and revision to some projects I have running and I use redbird as the reverse proxy as it has a very nice to use system. I hope its not dead but certainly does appear to be.

**Comment by manast** [comment]
It is not dead as far as I am concerned but I do not have so much time to spend on it, besides it does all I need it to do. Of course it can be cloned and maintained by others, but honestly, for niche projects like this one it is most likely not going to gain any traction.

**Comment by manast** [comment]
I am bringing Redbird another go. I am modernizing the code, updating dependencies, improving and adding new features. The cool thing is that using BunJS it is super fast now, I get up to 18k reqs/sec in my local M2 Pro computer. Soon there will be more news.

**Comment by Reinitialized** [comment]
Wowie, I totally forgot about this 😓 

Awesome to hear you're modernizing RedBird using Bun! Bun is absolutely awesome and I love it a lot. Excited to see what comes of it :)

**Comment by manast** [comment]
Yeah, since last post I could get over 50k+ reqs/sec with Node v20. Finalising the typescript port now.
