### ISSUE TITLE
Red bird reverse proxy issue with meteor hostname+paths

### ISSUE THREAD

**Issue by AdityaDinesh** [OptimalBits/redbird#27]
I use Red bird reverse proxy for my meteor apps, it has been Fantastic, I  recently face the following issue. Any help is appreciated.

My requests are redirected correctly when i use the below configuration i.e subdomain

var proxy = require('redbird')({port: 80});

proxy.register("app1.example.com", "http://127.0.0.1:3000");
proxy.register("app2.example.com", "http://127.0.0.1:4000");
but when i use domain + paths like in the below configuration

var proxy = require('redbird')({port: 80});

proxy.register("http://127.0.0.1/a", "http://127.0.0.1:3000");
proxy.register("http://127.0.0.1/b", "http://127.0.0.1:4000");
i get the error "no valid route found for given source". Below is the screenshot from browser

![capture](https://cloud.githubusercontent.com/assets/1632875/11365611/7a34ec1e-929f-11e5-8e35-bc19f3d89be7.PNG). 

issue post on stack

http://stackoverflow.com/questions/33892447/red-bird-reverse-proxy-issue-with-meteor-hostnamepaths

Please let me know in case you require more information

**Comment by manast** [comment]
sorry for late response. Can you paste a minimal code that reproduces this issue so that I can debug it?

**Comment by AdityaDinesh** [comment]
I am afraid I need to ask you to install meteor framework to reproduce this 😀

Here are the steps I followed which I am sure will help identify the issue.

1. Create two demo apps i.e 
$ meteor create app1 
$ meteor create app2

2. Run app1 on 127.0.0.1:3000 and app2 on 127.0.0.1:4000, i.e by executing 
$meteor --port 3000 and 
$metror --port 4000

browse to these locations to make sure they are up and running 

3. Run Redbird server with below config

var proxy = require('redbird')({port: 80});

proxy.register("http://127.0.0.1/a", "http://127.0.0.1:3000");
proxy.register("http://127.0.0.1/b", "http://127.0.0.1:4000");

Browse to http://127.0.0.1/a to get the error "no valid route found for given source". Any help is appreciated. Please let me know if you need more info. We are seriously considering Redbird for all our enterprise apps

**Comment by manast** [comment]
I created a simple test that works:
```
var proxy = require('../index')({port: 8080});

proxy.register("http://127.0.0.1/a", "http://127.0.0.1:3000");
proxy.register("http://127.0.0.1/b", "http://127.0.0.1:4000");

startServer(3000);
startServer(4000);

function startServer(port){
  var http = require('http');
  function handleRequest(request, response){
    response.end('Path Hit: ' + request.url);
  }
  var server = http.createServer(handleRequest);

  server.listen(port, function(){
    console.log("Server listening on: http://localhost:%s", port);
  });
}
```
I also made a new release which logs out the url that is actually not being served correctly. For instance, in this particular case, the browser tries to get /favicon.ico which is not a valid path for redbird.

**Comment by manast** [comment]
@AdityaDinesh do you have something more regarding this issue? feel comment and I can reopen it if that is the case.
