### ISSUE TITLE
0.10.0+ release?

### ISSUE THREAD

**Issue by cactysman** [OptimalBits/redbird#272]
Hi there,

I've been using redbird as a module in my custom reverse-proxy for a good few weeks now, but I noticed there's been a few useful changes to it since the latest release on the NPM registry in **2019** and I'd like to ask if it's possible (if stuff is stable/reliable enough of course) to release a dedicated upgraded version.

I know I could just create a fork or require the package from GitHub, but I'm not really a fan of that and it would also signal that [redbird isn't dead yet](267#issuecomment-737329226).

I'm not too familiar with the internals of redbird, but if there's anything that would make a timely release flush improbable, I'd like to offer helping with whatever's there to do.

Thanks for this great module.

**Comment by manast** [comment]
v1.0.2 is the latest most stable version as of now, it should be safe to upgrade but there may be small changes in the API, the best is to use typescript if you can to detect these changes.
