### ISSUE TITLE
Not listening to IPv4

### ISSUE THREAD

**Issue by lusvelt** [OptimalBits/redbird#282]
I have multiple apps running on my server and i have installed redbird to run multiple domains on the same server, each one addressing a specific app. However when I launch redbird (via pm2) it only listens from IPv6 addresses, as I can verify by running `netstat -tulpn`. Is this default behaviour or is there something wrong in my configuration?

```
const redbird = new require('redbird')({
        port: 80,
        letsencrypt: {
                path: 'certs',
                port: 3000
        },
        ssl: {
                port: 443
        }
});
```

**Comment by manast** [comment]
Sorry for late reply here. This is definitely something specific to your setup, the options looks correct, and I cannot reproduce it. Reopen if more instructions on how to reproduce it are provided.
