### ISSUE TITLE
Build failure in master branch HEAD as of commit cb7781e

### ISSUE THREAD

**Issue by hillct** [OptimalBits/redbird#283]
It appears the master branch as currently checked in, results in a build failure.
As of this writing master HEAD is https://github.com/OptimalBits/redbird/commit/cb7781e9c471bcb497ea4af1ddabf4fdf4432caa

I've not yet rolled back systematically to find a buildable version/commit point. FYI the Dockerfile doesn't' seem to present a usable build environment at this point either. As others have pointed out, the last connit was 3 years ago, so if the core developers could provide an update on the status of this project, that would b very helpful.

The relevant portion of the build log is below and I'll attach the full build log shortly:

1824 timing build:link Completed in 28ms
1825 info run deasync@0.1.14 install node_modules/deasync node ./build.js
1826 info run deasync@0.1.14 install { code: 1, signal: null }
1827 timing reify:rollback:createSparse Completed in 952ms
1828 timing reify:rollback:retireShallow Completed in 0ms
1829 timing command:install Completed in 14773ms
1830 verbose stack Error: command failed
1830 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1830 verbose stack     at ChildProcess.emit (node:events:390:28)
1830 verbose stack     at maybeClose (node:internal/child_process:1062:16)
1830 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
1831 verbose pkgid deasync@0.1.14
1832 verbose cwd /home/hillct/pinnacledigital/redbird
1833 verbose Linux 3.10.0-693.11.6.el7.x86_64
1834 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1835 verbose node v17.3.0
1836 verbose npm  v8.3.0
1837 error code 1
1838 error path /home/hillct/pinnacledigital/redbird/node_modules/deasync
1839 error command failed
1840 error command sh -c node ./build.js
1841 error make: Entering directory `/home/hillct/pinnacledigital/redbird/node_modules/deasync/build'
1841 error   CXX(target) Release/obj.target/deasync/src/deasync.o
1841 error make: Leaving directory `/home/hillct/pinnacledigital/redbird/node_modules/deasync/build'
1842 error gyp info it worked if it ends with ok
1842 error gyp info using node-gyp@8.4.1
1842 error gyp info using node@17.3.0 | linux | x64
1842 error gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
1842 error gyp info spawn /usr/bin/python3
1842 error gyp info spawn args [
1842 error gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
1842 error gyp info spawn args   'binding.gyp',
1842 error gyp info spawn args   '-f',
1842 error gyp info spawn args   'make',
1842 error gyp info spawn args   '-I',
1842 error gyp info spawn args   '/home/hillct/pinnacledigital/redbird/node_modules/deasync/build/config.gypi',
1842 error gyp info spawn args   '-I',
1842 error gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
1842 error gyp info spawn args   '-I',
1842 error gyp info spawn args   '/home/hillct/.cache/node-gyp/17.3.0/include/node/common.gypi',
1842 error gyp info spawn args   '-Dlibrary=shared_library',
1842 error gyp info spawn args   '-Dvisibility=default',
1842 error gyp info spawn args   '-Dnode_root_dir=/home/hillct/.cache/node-gyp/17.3.0',
1842 error gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
1842 error gyp info spawn args   '-Dnode_lib_file=/home/hillct/.cache/node-gyp/17.3.0/<(target_arch)/node.lib',
1842 error gyp info spawn args   '-Dmodule_root_dir=/home/hillct/pinnacledigital/redbird/node_modules/deasync',
1842 error gyp info spawn args   '-Dnode_engine=v8',
1842 error gyp info spawn args   '--depth=.',
1842 error gyp info spawn args   '--no-parallel',
1842 error gyp info spawn args   '--generator-output',
1842 error gyp info spawn args   'build',
1842 error gyp info spawn args   '-Goutput_dir=.'
1842 error gyp info spawn args ]
1842 error gyp info spawn make
1842 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
1842 error g++: error: unrecognized command line option ‘-std=gnu++17’
1842 error make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
1842 error gyp ERR! build error 
1842 error gyp ERR! stack Error: `make` failed with exit code: 2
1842 error gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
1842 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
1842 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
1842 error gyp ERR! System Linux 3.10.0-693.11.6.el7.x86_64
1842 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
1842 error gyp ERR! cwd /home/hillct/pinnacledigital/redbird/node_modules/deasync
1842 error gyp ERR! node -v v17.3.0
1842 error gyp ERR! node-gyp -v v8.4.1
1842 error gyp ERR! not ok 
1842 error Build failed
1843 verbose exit 1
1844 timing npm Completed in 15211ms
1845 verbose unfinished npm timer reify 1682794903321
1846 verbose unfinished npm timer reify:build 1682794916093
1847 verbose unfinished npm timer build 1682794916097
1848 verbose unfinished npm timer build:deps 1682794916098
1849 verbose unfinished npm timer build:run:install 1682794916160
1850 verbose unfinished npm timer build:run:install:node_modules/deasync 1682794916160
1851 verbose code 1

**Comment by manast** [comment]
This issue should not exist anymore on v1 of Redbird as all dependencies have been upgraded and the code ported to typescript.
