### ISSUE TITLE
Production usage?

### ISSUE THREAD

**Issue by alexgorbatchev** [OptimalBits/redbird#3]
This looks pretty great feature wise. Curious if it's battle tested, where and how?

**Comment by manast** [comment]
We have been using redbird for over a year now. Quite stable and nice to use. Our setup includes dozens of backend servers reverse proxied by redbird, some of them use HTTPS others just plain HTTP.

**Comment by AlexanderElias** [comment]
@manast any chance you might provide us a performance comparision to nginx?
