### ISSUE TITLE
"Module not found" errors

### ISSUE THREAD

**Issue by Andicraft** [OptimalBits/redbird#306]
Started a very basic project using `npm init` - any attempts to import Redbird failed.

The issue seems to be that `package.json` doesn't specify a main entry point, so it defaults to 'index.js' at the package root - which doesn't exist.

Ended up switching the base module to module type and doing `import { Redbird } from 'redbird';` instead of `require('redbird')`.

**Comment by manast** [comment]
Thanks for reporting this. Let me know if you find any other issues.
