### ISSUE TITLE
HTTPS -> HTTPS passthrough

### ISSUE THREAD

**Issue by avinash-bhatia** [OptimalBits/redbird#31]
Hi,

First of all, thanks for the great work. We intend to use Redbird in our Production environment due to it's ease of programming and automation.

This is a (pair of) questions - not a bug report, or a feature request:

(a) Is there a way to specify an HTTPS->HTTPS passthrough mode with just a port re-direction ? I couldn't find an obvious way to do it from the documentation.

(b) Once the "ssl" is specified during the instantiation of the proxy, it seems then that only HTTPS requests are honoured and it's not possible to proxy an plain HTTP request. Is my understanding correct ?

Thanks,
Avinash

**Comment by manast** [comment]
HTTPS -> HTTPS is a missing feature. May be easy to implement, but I have not prioritized it so much. Regarding question b), just use set the option redirect to false in the ssl options (check the README), so you can use HTTP and HTTPS with the same route.
