### ISSUE TITLE
load host/port data from a json file?

### ISSUE THREAD

**Issue by gavinengel** [OptimalBits/redbird#32]
Any thoughts about saving host/port data in a json file, to make it easier to load in various HTTP proxy daemons?  

```
{
	"hosts": [{
		"host": "abc.example.com",
		"targets": ["http://172.17.40.6:8080"]
	}, {
		"host": "abc.example.com/media",
		"targets": ["http://172.17.40.6:8081"]
	}, {
		"host": "abc2.example.com",
		"targets": ["http://172.17.40.6:8080", "http://172.17.41.6:8080", "http://172.17.42.6:8080"]
	}]
}
```

I've been playing with various HTTP reverse proxies lately, and it would be great to use a json file to store this data (or rely on CoreOS etcd like Gogeta does).  It would make it easier to swap between various proxyd for testing.

**Comment by manast** [comment]
This could be implemented easily on top of redbird, just by "requiring" the json file and then calling register for the hosts array. If this is a very common and useful case, I could consider to put a helper function, or enhance the register function to take an array as input with the table of values.

**Comment by gavinengel** [comment]
OK, if you have time.  If not no prob.
