### ISSUE TITLE
Docker DNS question

### ISSUE THREAD

**Issue by gavinengel** [OptimalBits/redbird#33]
To connect to a pre-existing Docker container, I use this:

`proxy.register("www.example.com", "172.17.0.13");`

Here is my question: Can I specify a container's name instead of it's private IP address?

`proxy.register("www.example.com", "some-container");`

I do see that there is support for brand new containers, but since mine are generic images like `ubuntu` and because they are pre-exisiting I don't believe this can help me:

```
require('redbird')
  .docker(redbird)
  .register("example.com", 'company/myimage:latest');
```

**Comment by manast** [comment]
Currently it is not possible to use a container name. The rationale is that we want to support many containers from the same image and get automatic load balancing and zero downtime. One simple workaround for you would be to create a new image based on your generic image and use that instead.

**Comment by gavinengel** [comment]
Oh that makes sense. I see how that would make my project more stable as well.  Thanks!
