### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by dylmye** [OptimalBits/redbird#41]
Hi! I really want to use bower for my project management but currently I am using 99% bower, and 1% NPM - just for this project. 

I believe all you have to do is add the following to your `package.json` root:
`"main": "index.js",`

That'd be great.

Thanks!

**Comment by manast** [comment]
thanks for the patch. I am wondering, isn't bower designed for handling client side dependencies? I am curious about knowing more about your setup, since redbird runs on node and node include npm by default.

**Comment by dylmye** [comment]
http://stackoverflow.com/a/18652918    
You might be right, I have no clue. I just want to use hatena-server for my nodejs project.    
What I'm trying to make is a server accessible from a domain I don't own. Sounds nefarious but see [my project.](https://github.com/dylmye/hatena-server) There I'm using redbird as a central part of my code.

**Comment by manast** [comment]
I see. You should use a package.json file in your project where you define your dependencies, then just do a npm install. No need to install every package by hand. Same thing for bower packages.
Easiest is to init your project with npm init. That will create a default package.json, after that do for example npm install redbird --save  and it will add it automatically to the package.json dependencies (same for all the modules that your server depends upon).
