### ISSUE TITLE
mod_rewrite similar usage?

### ISSUE THREAD

**Issue by dylmye** [OptimalBits/redbird#43]
Hi,

I would like to serve `http://foo.com/abc/x/y.jpg` as `http://foo.com/abc?first=x&second=y&type=jpg`.

Is this possible with redbird? I don't see regex as an option.

**Comment by manast** [comment]
no, redbird is not a url remapper so to speak, it is a reverse proxy, so you can only map hosts (including paths) to another host.

**Comment by dylmye** [comment]
Would you be able to suggest a package that would let me do so in Node? I don't really know what to search. 

Thanks!

**Comment by manast** [comment]
Something like this maybe? https://github.com/tinganho/connect-modrewrite

**Comment by dylmye** [comment]
Thanks!
