### ISSUE TITLE
Path Based Routing

### ISSUE THREAD

**Issue by logbon72** [OptimalBits/redbird#47]
This is a great server! Just one question, I will like to route all requests to a particular path (irrespective of the host) to an upstream server. As an example 

    **/api -->      http://127.0.0.1:8080
    **/office ---> http://127.0.0.1:9999

Is this achievable with the current version? 

Another question, any plans to allow weight assignment to the servers in the case of load-balancing?

**Comment by manast** [comment]
I guess you answered this questions yourself since you created a PR that resolved them :)
