### ISSUE TITLE
Cannot redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by hckhanh** [OptimalBits/redbird#50]
Hi @manast, I am using this module in my project. But I didn't see it redirect from HTTP to HTTPS automatically. I think it does not work.

- Domain: example.com
- Node.js port: `3000`
- Redbird port: `4001`
- Redbird SSL port: `4000`

Here is my implementation:

```javascript
/**
 * Main domain of the app.
 */

const DOMAIN_NAME = 'example.com';

/**
 * Create HTTPS proxy server.
 */

const proxy = redbird({
  port: 4001,
  ssl: {
    port: 4000,
    key: `config/ssl/${DOMAIN_NAME}.key`,
    cert: `config/ssl/${DOMAIN_NAME}.crt`,
    ca: `config/ssl/${DOMAIN_NAME}.ca-bundle`
  }
});

/**
 * Listen on provided port and map domain to the app.
 */

proxy.register(DOMAIN_NAME, 'http://localhost:3000', { ssl: true });

/**
 * Get port from environment and store in Express.
 */

const port = normalizePort(config.port);
app.set('port', port);

/**
 * Create HTTP server.
 */

const server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(3000);
```

**Comment by hckhanh** [comment]
When I test it with `curl`, It works correctly, but it does not works on Google Chrome.

```
 Rebuilt URL to: example.com:4001/
 timeout on name lookup is not supported
   Trying 127.0.0.1...
 Connected to giveta.org (127.0.0.1) port 4001 (#0)
 GET / HTTP/1.1
 Host: example.com:4001
 User-Agent: curl/7.47.1
 Accept: */*

 HTTP/1.1 302 Found
 Location: https://example.com:4000\
 Date: Mon, 30 May 2016 05:01:28 GMT
 Connection: keep-alive
 Transfer-Encoding: chunked

 Connection #0 to host giveta.org left intact
```

I think it should be `301` **Moved Permanently**.

**Comment by manast** [comment]
I do not think there is any major difference between 301 or 302 for chrome. It is working well for me, I cannot reproduce your issue...

**Comment by timjongun** [comment]
For anybody still having this problem, I experienced it as well. In my case, the curl was succeeding while Chrome failed because I didn't have the correct ports open on my firewall. Ensure that both the `http` and `https` port that you've specified in your settings are open on your firewall if you're using one.
