### ISSUE TITLE
FYI Redwire was heavily inspired by Redbird

### ISSUE THREAD

**Issue by tcoats** [OptimalBits/redbird#51]
[Redwire](https://github.com/metocean/redwire)

I've implemented some things similar and some things differently.
It has been running in production for a year and a half now.

Features that were new at the time:
- Middleware
- Swapping configuration at runtime ([redwire-harmony](https://github.com/metocean/redwire-harmony))
- `*` support (but not full regex, e.g. `*.domain.com`)

It would be interesting to see if any parts are common and potentially even merging the projects.

**Comment by manast** [comment]
is there anything redbird can do that redwire can't? :)

**Comment by manast** [comment]
jokes aside. I like redwire's api. Its quite nice and flexible. We (and others) have also been using redbird for several years in production, so I know it is quite stable. One of the features I like in redbird is the docker support. Maybe we can enhance redbird with redwires middleware syntax. It seems as for some reason gained some traction, maybe its wiser to use redbird's "brand". somehow we would need to keep redbird backwards compatible though...
