### ISSUE TITLE
Support upper case in the domain

### ISSUE THREAD

**Issue by yeya** [OptimalBits/redbird#57]
Hi there

It looks like redbird can not proxy requests with upper cases.
I have old clients trying to get to Support.example.com.
I tried to:
`proxy.register("Support.example.com", "http://localhost:1234");`
but redbird ignore the uppercase, so I always get:
> "msg":"no valid route found for given source"

**Comment by manast** [comment]
domain names should be case insensitive, this is a bug in redbird.

**Comment by yeya** [comment]
Great!!! Thank you.
Can you please just update the version to allow easy fix by npm update?

**Comment by manast** [comment]
done!.
