### ISSUE TITLE
Request is pending when the redirect server is down

### ISSUE THREAD

**Issue by slavik57** [OptimalBits/redbird#59]
When the destination server is down, I see in the log:
`{"name":"redbird","hostname":"myLaptop","pid":5664,"level":50,"err":{"message":"connect ECONNREFUSED 127.0.0.1:8021","name":"Error","stack":"Error: connect ECONNREFUSED 127.0.0.1:8021\n    at Object.exports._errnoException (util.js:874:11)\n    at exports._exceptionWithHostPort (util.js:897:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)","code":"ECONNREFUSED"},"msg":"Proxy Error","time":"2016-07-02T15:03:54.155Z","v":0}`

And the request is pending on the chrome..

**Comment by slavik57** [comment]
When do you think you will fix it?

**Comment by manast** [comment]
I have been quite busy lately sorry. I will try to find some time for this in short.

**Comment by Siedrix** [comment]
I was reviewing this, is it something more complex than adding a `res.end()` on the handleProxyError?

I can fix this if you tell me what the expected behavior is.

**Comment by slavik57** [comment]
Well if the server is down behind it, then it should return a 404 NotFound error because it cannot find the url configured

**Comment by Siedrix** [comment]
Are you sure that the response is a 404 and not a 502 bad gateway?

**Comment by slavik57** [comment]
Yes it would be better

**Comment by Siedrix** [comment]
I created this pull request, let me know if you need any change. https://github.com/OptimalBits/redbird/pull/60

**Comment by slavik57** [comment]
Looks good to me

**Comment by manast** [comment]
For some reason it is not returning 502 in the unit test, but at least it should not keep hanging the request since it is calling end().

**Comment by Siedrix** [comment]
Unit tests are fixed now

**Comment by Siedrix** [comment]
Now that the branch is merged, shoudl we close this issue? is there anything else to fix?

**Comment by slavik57** [comment]
If you checked it and it works you can close it...when will it be on the npm?
