### ISSUE TITLE
Cannot connect to parse server. "Cannot GET /" and 'XMLHttpRequest failed: "Unable to connect to the Parse API"

### ISSUE THREAD

**Issue by MostHated** [OptimalBits/redbird#64]
Hello,
    I am not 100% sure this is an issue with redbird at all, but I am not able to figure it out. My pal and I are working on getting a store he made working using nodejs, I also am running apache on 8080 and 8443 in order for them to run side by side and am using redbird to handle the requests, but for some reason I am not able to get the store to connect to parse-server, yet parse dash is working fine.

Here is what I am using currently. 

`//If URL has/.well-known/, send request to upstream API service
  var customResolver1 = function(host, url) {
   if(/^\/.well-known\//.test(url)){
      return 'http://planetex.press:8080';
   } 
 };

 //assign high priority
 customResolver1.priority = 100;

 var proxy = new require('redbird')({
    port: 80, 
    resolvers: [
    customResolver1],
    secure: true,
    ssl:{ port: 443 },
 })

proxy.register("www.planetex.press", "http://www.planetex.press:3000", {
ssl: {
        key: "/home/planetex/ssl.key",
        cert: "/home/planetex/ssl.cert",
    }
});
proxy.register("api.planetex.press", "http://api.planetex.press:3002",{
ssl: {
        key: "/home/planetex/domains/api.planetex.press/ssl.key",
        cert: "/home/planetex/domains/api.planetex.press/ssl.cert",
    }
});
proxy.register("dash.planetex.press", "http://dash.planetex.press:3001",{
ssl: {
        key: "/home/planetex/domains/dash.planetex.press/ssl.key",
        cert: "/home/planetex/domains/dash.planetex.press/ssl.cert",
    }
});`

**Comment by manast** [comment]
maybe you should try without the custom resolver to see if that is somehow affecting, custom resolvers are new functionality and maybe there is some unknown issue. Also when registering routes, do not put the protocol (http) in front of the route, just the domain and port.

**Comment by MostHated** [comment]
Thank you for the reply. the customer resolver is honestly the whole point and what made me wants to use this application to begin with, otherwise I would not need to use this at all, it is to let Letsencrypt verify the domain identity to obtain SSL certificates.  That being said, removing it as well as the http:// from the other ones made no difference.

I made a new DigitalOcean droplet using only nginx as the reverse proxy and the store work just fine, but unfortunately will also not help letting the domain/.well-known/acme-challenge work, as things hitting port 80 would then just be redirected to the node port. 

If you have any other ideas or suggestions, please do let me know!

**Comment by manast** [comment]
I am quite interested in letsencrypt, if you can provide me some minimal example I can debug it.

**Comment by MostHated** [comment]
Sure thing, I go about it a different way ever since http://virtualmin.com integrated letsencrypt to their web hosting panel. You just input a domain name, it setups up the DNS, MySQL, all postfix / dovecot, Apache, everything. Then you just hit "Manage SSL", select letsencrypt, put in the domains you want to secure (www.domain.com, api.domain.com, etc) and what happens is, the locally installed letsencrypt client creates a folder in /home/domain/public_html/.well-known/acme-challenge/Aasf3ggeG(bunch of random stuff) and then letsencrypts servers attempt to go to that url in order to verify that you are the owner of that domain, and once it does it reports back to the locally installed client and creates your free SSL certificate. Virtualmin has a built in renewal manager, (letsencrypt certs last for 3 months) so you just set the renewal to something like 2 months and it will automatically renew for you, free, forever.

The other way to test is, if you have apache you download certbot from https://certbot.eff.org/#ubuntutrusty-apache (the main page lets you select any webserver variation such as apache, nginx, or technically just none and it can manually create a cert without verifying, but for simplicity of working with virtualmin's auto installation and renewal, that is why I want this to work),  and you simply install it, run certbot-auto --apache and it will find the installed websites, you fill out a bit of info, such as email address to be associated with the cert, etc, and then you can script it to run every 3 months, 1 month, every day even to renew with certbot-auto renew, and it handles it all.

The main thing though when working with node and apache, is to have my domain go straight to my node app, I have to use the reverse proxy with the custom resolver so that when letsencrypt tries to access domain.com/.well-known/acme-challenge/randomfile it can get to it, which I am sure you can tell from the code I posted. It works perfectly well for that the way I have it setup, but for some reason it just is not allowing my node application to get to parse-server. 

The strangest thing is parse-dash can get to it, but not the other application, which gave the error above. As I mentioned earlier though, if I just use nginx proxy with nothing else and have it point the domain to port 3000 for my site, 3001 for parse, and 3002 for the dash, it works fine and I just can not figure out for the life of my why I can not do it with redbird. I do not think I can accomplish what I am after, letting letsencrypt get past the node app without doing this with the proxy. 

I very much appreciate you taking the time to look in to this, I am excited to have this working.

**Comment by manast** [comment]
I will try to create the same setup locally to see if I can reproduce it. After that it should be easy to find the problem.

**Comment by manast** [comment]
did you notice that this url is not working? 
http://api.planetex.press:3002

does not seem to have to do with redbird, it is just proxying correctly, but the target server responds with a 404 Not Found

**Comment by MostHated** [comment]
Well, that is the thing, my friend who is developing the application (http://www.planetex.press) he was getting the "unauthorized" message that parse server gives typically, but when he updated (npm install) he started to get the same message of "Cannot GET /". https://api2.planetex.press/ is the test server, which is the one running nginx and working perfectly fine, gives the same message. It is something to do with an update to parse, it looks like. https://dash2.planetex.press, as well as https://ww2.planetex.press all are on a test droplet and work perfectly, even with the parse error you see when going to it directly.

**Comment by manast** [comment]
I think you need to figure out why you cannot access the url directly, when we understand why is that we can attack the problem, otherwise it is very difficult to guess why it is not working.

**Comment by manast** [comment]
Btw, you may be interested in this: https://github.com/OptimalBits/redbird/commit/997626cd1221a6e5314def664e036350b9a4caef

I need to implement the automatic renewal procedure and more testing, but other than that this is mostly finished.

**Comment by MostHated** [comment]
Oh awesome! Very much appreciate that. It will make things a ton easier, lol.

**Comment by MostHated** [comment]
I seem to be having a bit of a redirection loop or something going on when trying to get to my node port. It is also saying that my fullchain.pem is not right for www.planetex.press. I reworked my config to match your readme, it looks like it got / made the certs, but something is not working right still.

**Comment by manast** [comment]
you should not specify certs and key at the same time as you are using letsencrypt (I will make a check so that you get an informative error if you do). Also, what version of nodejs are you using? I think you need 4.5 for this to work optimally.

**Comment by MostHated** [comment]
I originally did not specify them, I only did for testing purposes and I still had the same issues both with and without. I am using Node 4.5.0. Below is the node log when starting up the server and then going to the web address.

http://hastebin.com/osipurofih.coffee

**Comment by manast** [comment]
The logs looks correct, can it be that the port 443 is not open on your host machine? when you try to access via https, do you get any logs in redbird? if you don't it means that the request is not reaching redbird at all.

**Comment by manast** [comment]
ok, it seems that it is working now... enable the production flag when you are satisfied to get a green url bar :)

**Comment by MostHated** [comment]
It definitely looks like it is, I enabled production, yet it is still doing it. When I first enter the URL of www.planetex.press/ it hangs for about 10 seconds, then goes to https://www.planetex.press/, but is still not showing a valid certificate for some reason. If I refresh a few times, I will see it show it for a second, but then another redirect happens directly to :443 instead of 3000 as seen below.

{"name":"redbird","hostname":"ubuntu-1gb-nyc3-01","pid":22617,"level":30,"msg":"Proxying www.planetex.press/ to www.planetex.press:3000/","time":"2016-08-31T18:54:09.151Z","v":0}
proxy-2 {"name":"redbird","hostname":"ubuntu-1gb-nyc3-01","pid":22617,"level":30,"msg":"Redirecting www.planetex.press/ to https://www.planetex.press:443/","time":"2016-08-31T18:54:09.155Z","v":0}

**Comment by manast** [comment]
maybe this is a special case not supported at the moment. i.e., enabling https on the same domain that you are reverse proxyn to. This is how the logs look like when it works correctly:
```
[2016-08-31T19:08:43.055Z]  INFO: redbird/1 on db48469df95c: Proxying caturra.exactbytes.com/ to 127.0.0.1:3000/
[2016-08-31T19:08:43.055Z]  INFO: redbird/1 on db48469df95c: Redirecting caturra.exactbytes.com/ to https://caturra.exactbytes.com:443/
[2016-08-31T19:08:43.098Z]  INFO: redbird/1 on db48469df95c: Proxying caturra.exactbytes.com/ to 127.0.0.1:3000/
```
As you can see I am proxyn to a server in 127.0.0.1:3000

**Comment by manast** [comment]
btw, when activating the flag for production you probably need to delete the certs directory, otherwise he will use the existing one until it expires.

**Comment by MostHated** [comment]
Ok, looks we are headed in the right direction! I changed my config to the following : 

`proxy.register("www.planetex.press", "127.0.0.1:3000", {
ssl: {
	letsencrypt: {
    	email: 'm374llic4@gmail.com', // Domain owner/admin email
    	production: true, // WARNING: Only use this flag when the proxy is verified to work correctly to avoid being banned!
    	}
    }
});

Though it hangs for about 5-10 seconds when going to http://www.planetex.press `for some reason, showing nothing in the logs until after those seconds.

**Comment by manast** [comment]
good that it works now, but I think it is quite strange that it takes some extra time first time you access. The certificates are generated as soon as you start the proxy and if they are already generated it just reads the cached ones very quickly... so there should not be any delay.

**Comment by MostHated** [comment]
There only seems to be delay when first starting /restarting my proxy.js, after a minute or so everything is fine. There were a few errors during the sal generation process.  I will send for your diagnostics once I am at a pc (was an overflow of some kind if I remember correctly). 
Other than those things it is working great,  I very much appreciate the time and effort you put in to this. 
 
 
  On Wed, Aug 31, 2016 at 5:28 PM, Manuel Astudillo<notifications@github.com> wrote:   
good that it works now, but I think it is quite strange that it takes some extra time first time you access. The certificates are generated as soon as you start the proxy and if they are already generated it just reads the cached ones very quickly... so there should not be any delay.

**Comment by manast** [comment]
@MostHated do you have any updates? is it working for you?

**Comment by MostHated** [comment]
@manast Yes sir, everything has been working quite well. 👍 Have not ran into any more issues so far.

**Comment by MostHated** [comment]
Any plans on getting the failover up and running? I keep trying to find a nodejs based DNS server that has failover, the only one I have found has not had a commit in 4 years, and is not working properly, unfortunately. : /
