### ISSUE TITLE
subpath

### ISSUE THREAD

**Issue by csakaszamok** [OptimalBits/redbird#67]
Hi!

I created a web app and a redbird reverse proxy app.

Reverse proxy app:
```
..
var proxy = require('redbird')({port: 80});
proxy.register("127.0.0.1/web1", "http://127.0.0.1:3000");
..
```
Web1 app:
```
..
<p>Test site 1</p>
<img src="images.jpg">
..
```

- http://127.0.0.1:3000
Test site 1 msg is ok.
Image is ok.
=> Web1 app works fine.

- http://127.0.0.1/web1
Test site 1 msg is ok.
Image is 404 because the request url is still http://127.0.0.1/images.jpg

What is wrong?

**Comment by manast** [comment]
I think you should put the source to images to /web1/images.jpg

**Comment by csakaszamok** [comment]
if i modify the references in source code then how can work it in an another server (same source code) ?

**Comment by manast** [comment]
Try this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
