### ISSUE TITLE
Keep-Alive Http Agent for proxy server

### ISSUE THREAD

**Issue by FilipMatys** [OptimalBits/redbird#68]
Hi,

First of all, thank You, we use redbird and works like a charm. But there is one thing. We would like to use keep-alive connection, but right now, the connection is 'close'. I have found in Your code commented out agent for proxy server to allow keep-alive connections. 

Is there any particular reason for that? Any issues it can cause? I found nothing nor in issues nor in documentation.

Best regards
Filip

**Comment by manast** [comment]
I was experimenting with it and just left it out commented.  Keep-alive increases performance quite a lot, around 4x. An easy way to enable it is by setting the value globally like this:
```
http.globalAgent = new http.Agent({ keepAlive: true });
https.globalAgent = new https.Agent({ keepAlive: true });
```
I will add this as a setting in an upcoming version. Btw, you may be interested in this thread regarding performance:
https://github.com/nodejitsu/node-http-proxy/issues/1058

**Comment by FilipMatys** [comment]
That is great. Thank you!

**Comment by aek** [comment]
@manast awesome performance thread. But as I am new to redbird... Could you give us some kind of news about the performance topics discussed around the solutions that beat nginx? Is there something already implemented in the redbird core that is not using node-http-proxy? And what scenarios could be afected by moving away from node-http-proxy?

**Comment by manast** [comment]
Currently the proxy part is performed using node-http-proxy, so performance equals that module. It should be possible to replace that module with a lighter proxy based on node streams, but I have not time for that right now.
