### ISSUE TITLE
async custom resolvers

### ISSUE THREAD

**Issue by kingkrausel** [OptimalBits/redbird#71]
Hi,

is there a way to have async/promise-based custom resolvers? This would be a useful feature for us, since have to  request the target IP from a consul service.

**Comment by manast** [comment]
Thats is not possible, but I wonder if you wont loose a lot of performance. Can't you instead register routes based on consul as the etcd backend is doing?

**Comment by kingkrausel** [comment]
We planned to cache the IPs as long as the requests are valid. However, it is probably more convenient to do it like it's done for etcd.
