### ISSUE TITLE
Unable to locate Docker container IP address

### ISSUE THREAD

**Issue by jgrenon** [OptimalBits/redbird#78]
I'm running a docker-swarm service with 2 containers. They are properly detected when redbird launches (and when they are started), but the code below is not able to handle multiple networks. My containers are running in two networks (internal and proxy). Redbird is running in the proxy network. At container registration time, the detected IPAddress is null. 

```javascript
function containerPort(dolphin, containerId) {
  return dolphin.containers.inspect(containerId).then(function (container) {
    var port = Object.keys(container.NetworkSettings.Ports)[0].split('/')[0];
    var ip = container.NetworkSettings.IPAddress;
    if (port && ip) {
      return 'http://' + ip + ':' + port;
    } else {
      throw Error('No valid address or port ' + container.IPAddress + ':' + port);
    }
  });
}
```

I've modified the code to show where we should get the IPAddress. I need help to create a reusable solution (some config objects where we could indicate how to locate the IP, which network maybe). 

```javascript
function containerPort(dolphin, containerId) {
  return dolphin.containers.inspect(containerId).then(function (container) {
    var port = Object.keys(container.NetworkSettings.Ports)[0].split('/')[0];
    var ip = container.NetworkSettings.Networks.proxy.IPAddress;
    if (port && ip) {
      return 'http://' + ip + ':' + port;
    } else {
      throw Error('No valid address or port ' + container.NetworkSettings.Networks.proxy.IPAddress + ':' + port);
    }
  });
}
```

I can implement the solution, just need input to design it properly. Is the config approach the best one? Should these options be passed in registerContainer options? Based on Docker doc, sounds like this is the new way to get container IP, even when a single network is used (https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#list-containers)

**Comment by MartinsThiago** [comment]
I started the pull request #75 where I modified this code

I changed the code for retrieving the ip from network (if there's only one), but I didn't have time to finish it yet... You can see it here https://github.com/OptimalBits/redbird/pull/75/files#diff-f68e1ed72a6a9bbc03d6989560fa9708R156

**Comment by MartinsThiago** [comment]
My PR has 3 TODOS :disappointed:

**Comment by manast** [comment]
when using swarm mode and networks, you do not need to use the redbird docker module, just register the proxy rule by using the service name. For example, if you have a service called 'my-backend' exposing port 8000:
```
redbird.register('mydomain.com', 'my-backend:8000');
```
Load balancing is performed by docker and the hostname is correctly routed by the routing mesh code in docker...

**Comment by jgrenon** [comment]
I confirm, I just referenced the service name and everything is properly linked. Simpler!

**Comment by aek** [comment]
This issue is solved then. It can be closed?
