### ISSUE TITLE
Redirect a HTTP POST to HTTPS POST using let's encrypt?

### ISSUE THREAD

**Issue by scwood** [OptimalBits/redbird#86]
When I try to curl a POST route in my application without HTTPS it fails. In the logs I can see that it's redirecting but it doesn't look like it's sending the POST through, and when I do it in Postman it says failed to GET. Any ideas?

**Comment by scwood** [comment]
After some research it looks like this isn't possible.

**Comment by dockmanaman** [comment]
1) create an application with redbird in https 
2) create  another application with redbird listening port 80  and for each domain you redirect to https website 

var proxy = require('redbird')({port: 80});
proxy.register("domain1.com", "https:/domain1.com");
proxy.register("domain2.eu", "https://domain2.eu");
proxy.register("forum.domain2.eu", "https://forum.domain2.eu");
