### ISSUE TITLE
TypeScript type definition file

### ISSUE THREAD

**Issue by JuergenGutsch** [OptimalBits/redbird#96]
Do you plan to provide a TypeScript  type definition file to https://github.com/DefinitelyTyped/DefinitelyTyped?
This would be great and makes it easier to use in TypeScript

**Comment by mofax** [comment]
is this in the pipeline?

**Comment by ChrisTalman** [comment]
It seems that no such file was provided, unless I'm mistaken?

If someone was willing to create one, would it be welcome in a pull request in this repository to be included as an `index.d.ts`, rather than in DefinitelyTyped?

**Comment by manast** [comment]
It is provided https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bull
and also bullmq (next major version of bull) it entirely written in typescript: https://github.com/taskforcesh/bullmq

**Comment by ChrisTalman** [comment]
Hey @manast.

Apologies, but that seems to be for `bull`, not `redbird`.

**Comment by larvanitis** [comment]
https://github.com/OptimalBits/redbird/issues/96#issuecomment-605814986 is about a different software.

Please reopen this issue.
