### ISSUE TITLE
Relative Path subfolder

### ISSUE THREAD

**Issue by markrey** [OptimalBits/redbird#97]
I have simple configuration where i am redirecting internal 3 docker applications as subdirectory of main domain.

```
proxy.register("main.example.com/site1", "http://0.0.0.0:8001");
proxy.register("main.example.com/site2", "http://0.0.0.0:8002");
proxy.register("main.example.com/site3", "http://0.0.0.0:8003");

```
Now all three sites have relative URLs for example:
`http://0.0.0.0:8001/asset/app.css` will have ` /asset/app.css` in config.

Now when `main.example.com/site1` loads it should get files from `main.example.com/site1/asset/app.css` rather than `main.example.com/asset/app.css`

Any suggestion how to solve it?

**Comment by Muhaah** [comment]
The problem is the file path in the HTML file.
Redbird do not touch the HTML file paths, so there is no solution.
You can modifier the paths in the HTML file to /siteX/asset/app.css

**Comment by markrey** [comment]
Thanks @Muhaah 
Closing as I went with bit different path.

**Comment by aek** [comment]
I have done something similar by allowing to configure paths in the
integration that i'm using it with etcd as backend, I have some
contributions to do it with this topic but I need to review some stuffs
first and do some code updates
The use of my changes is to allow to specify this kind of config
"{"paths": {"/longpolling": "54.84.243.63:8072/longpolling", "/": "
54.84.243.63:9000"}, "ssl": {"letsencrypt": {"production": true, "email": "
aekroft@gmail.com"}}}"

To the same domain name without the need to split this in different configs
and using the internal design of the data structure that store the proxy
paths. I think that this approach should be good to have in the code base,
I will issue a PR with this changes
